Python/Framword(Django)/django_subway/config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
   
    path('btest/' ,include('btest.urls')),
    path('crud/' , include('crud.urls')),
    path('subway/' , include('subway.urls')),
    path('admin/', admin.site.urls),

]

Python/Framword(Django)/django_subway/crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'
urlpatterns = [
    path('' , views.index , name= 'index'), #crud/
    path('new/' , views.new , name = 'new'), #crud/new
    # path('create/' , views.create , name='create'), #crud/create
    path('<int:art_pk>/', views.detail , name= 'detail'), #crud/detail하게 내용 보는 페이지
    path("<int:art_pk>/update/", views.update ,  name = 'update'), # crud/update/ 수정하는 페이지
    # path("<int:pk>/revise/" , views.revise , name = 'revise'),
    path("<int:art_pk>/delete/" , views.delete , name = 'delete'),
    path("<int:art_id>/comment" , views.comment , name='comment'),
    #부모의 아이디는 art_id로 바꿔주겠다. 
    path('<int:art_id>/comment/<int:com_id>/edit/' , views.comedit, name = 'comedit'),
    path('<int:art_id>/comment/<int:com_id>/del/' , views.comdel, name = 'comdel'),

]

Python/Framword(Django)/django_subway/subway/urls.py
from django.urls import path
from . import views

app_name = 'subway'
urlpatterns = [
    #name 을 설정하면 url관리가 수월하다.
    #{% url 'name설정한것' %} appname지정안했다면
    #{% url 'app_name:name설정한것' %} 위에 app name지정한다면
    #url이 바뀌어도 일일히 찾아서 바꿀 필요가 없다.
    path('' , views.index , name = 'index'),
    path('menu/' , views.menu , name='menu'), #메뉴 선택하는 링크
    # path('addmenu/' , views.addmenu, name = 'add'), #메뉴 추가 링크
    path('<int:id>/', views.detail , name = 'detail'),
    path('mod/<int:id>/' , views.mod , name  = 'mod'),
    path('delete/<int:id>/' , views.delete , name = "delete"),

    
]

Python/Framword(Django)/django_subway/subway/models.py
from django.db import models

# Create your models here.
class Subway(models.Model):
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=40)
    phone = models.IntegerField()
    bread = models.CharField(max_length=20)
    vegetable = models.CharField(max_length=20)
    sauce = models.CharField(max_length=20)
    drink = models.CharField(max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) # 수정일자 auto_now 생성일자 auto_now_add
    def __str__(self):
        return f'{self.name} : {self.create_at}' 

Python/Framword(Django)/django_subway/subway/views.py
from django.shortcuts import render , redirect
from subway.models import Subway



# Create your views here.
def index(request):
    sb = Subway.objects.all()
    context = {
        "sb" : sb
    }
    return render(request , "subway/index.html" , context)

def menu(request):
    if request.method == "POST":
        name = request.POST.get('name')
        print(name)
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        bread = request.POST.get('bread')
        sauce = request.POST.get('sauce')
        vegetable =[str(veg) for veg in request.POST.getlist('vegetable')]
        vegetable = ",".join(vegetable)
        drink = request.POST.get('drink')

        sb  = Subway()
        sb.name = name
        sb.address = address
        sb.phone = phone
        sb.bread = bread
        sb.vegetable = vegetable
        sb.sauce = sauce
        sb.drink = drink
        sb.save()

        print("완료")
        

        return redirect("subway:index")
    else :

        return render(request , "subway/menu.html")

def detail(request,id):
    sb =Subway.objects.get(id=id)
    context = {
        'sb' : sb
    }
    return render(request , "subway/detail.html" , context )

def mod(request, id):
    sb = Subway.objects.get(id=id)
    if request.method == 'POST':
        name = request.POST.get('name')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        bread = request.POST.get('bread')
        sauce = request.POST.get('sauce')
        vegetable =[str(veg) for veg in request.POST.getlist('vegetable')]
        vegetable = ",".join(vegetable)
        
        drink = request.POST.get('drink')

        sb  = Subway()
        sb.name = name
        sb.address = address
        sb.phone = phone
        sb.bread = bread
        sb.vegetable = vegetable
        sb.sauce = sauce
        sb.drink = drink
        sb.save()

        return redirect('subway:detail' , sb.id)
    else:
        context = {
            'sb' : sb
        }
        return render(request , 'subway/mod.html', context)

def delete(request , id):
    
    if request.method  == 'POST':
        sb = Subway.objects.get(id=id)    

        sb.delete()
        return redirect('subway:index')
    else:
        return redirect('subway:detail' , id)

Python/Framword(Django)/django_subway/subway/templates/subway/detail.html
{% extends 'base.html' %}
{% block body %}
<h1>주문자 {{sb.name }}의 메뉴</h1>
<hr>
<h3>{{ sb.bread }} 빵으로</h3>
<h3>{{ sb.sauce }} 소스를 발라</h3> 
<h3>{{ sb.vegetable }} 의 야채를 추가하여</h3> 
<h3>{{ sb.drink }} 와 마신다!</h3>
<h5>{{ sb.create_at }}</h5>

<a href = '{% url "subway:mod" sb.id %}'>수정하기</a>   
<form action='{% url "subway:delete" sb.id %}' method = 'POST'>
    {% csrf_token %}
    <input type= 'submit' value = "삭제하기">
</form>


{% endblock %}

Python/Framword(Django)/django_subway/subway/templates/subway/index.html
{% extends 'base.html' %} 

{% block body %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col"> 주문표</th>
        <th scope="col"> 이름</th>  
        <th scope="col"> 주문시간</th>
        
      </tr>
    </thead>
    <tbody>
    {% for ss in sb %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'subway:detail' ss.id %}">{{ss.name}}</a></td>
        <td><a href="{% url 'subway:detail' ss.id %}">{{ss.create_at}}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endblock %}

Python/Framword(Django)/django_subway/subway/templates/subway/menu.html
{% extends 'base.html' %}
{% block body %}
<form action='{% url "subway:menu"%}' method = 'POST'>
    {% csrf_token %}
    <h1>Subway 주문서</h1>
    <hr>
    이름 : <input type="text" name = "name" id = "name"><br>
    주소입력 : <input type="text" name = "address" id = "address"><br>
    전화번호 : <input type="tel" name = "phone" id = "phone"><br>
    <hr>
    <h3>메뉴 선택</h3>
    <h4>빵</h4>
    <select name="bread" id="bread">
        <option value="위트">위트</option>
        <option value="허니오트">허니오트</option> 
        <option value="플레인">플레인</option>
        <option value="하티">하티</option>
        <option value="오레아즈">오레아즈</option>
        <option value="플랫브레드">플랫브레드</option>
    
    </select>
    <h4>소스</h4>
    <input type="radio" name = "sauce" id = "sauce" value = "렌지">렌지
    <input type="radio" name = "sauce" id = "sauce" value = "마요네즈">마요네즈
    <input type="radio" name = "sauce" id = "sauce" value = "스위트어니언"> 스위트어니언
    <input type="radio" name = "sauce" id = "sauce" value = "스위트칠리"> 스위트칠리
    <input type="radio" name = "sauce" id = "sauce" value = "핫 칠리"> 핫 칠리
    <input type="radio" name = "sauce" id = "sauce" value = "올리브오일"> 올리브오일
    

    <h4>야채</h4>
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "양상추">양상추
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "토마토">토마토
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "오이">오이
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "피망">피망
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "양파">양파
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "피클">피클

    <h4>음료</h4>
    <input type="radio" name = "drink"  id = "drink" value = "콜라">콜라
    <input type="radio" name = "drink"  id = "drink" value = "스프라이트">스프라이트
    <input type="radio" name = "drink"  id = "drink" value = "환타">환타
    <input type="radio" name = "drink"  id = "drink" value = "쿨피스">쿨피스
    <input type="radio" name = "drink"  id = "drink" value = "오렌지쥬스">오렌지쥬스
    <br>
    <hr>
    <input type= 'submit'>
</form>
{% endblock %}

Python/Framword(Django)/django_subway/subway/templates/subway/mod.html
{% extends 'base.html' %}
{% block body %}
<form action='{% url "subway:mod" sb.id %}' method = 'POST'>
    {% csrf_token %}
    <h1>Subway 주문서</h1>
    <hr>
    이름 : <input type="text" name = "name" id = "name"><br>
    주소입력 : <input type="text" name = "address" id = "address"><br>
    전화번호 : <input type="tel" name = "phone" id = "phone"><br>
    <hr>
    <h3>메뉴 선택</h3>
    <h4>빵</h4>
    <select name="bread" id="bread">
        <option value="위트">위트</option>
        <option value="허니오트">허니오트</option> 
        <option value="플레인">플레인</option>
        <option value="하티">하티</option>
        <option value="오레아즈">오레아즈</option>
        <option value="플랫브레드">플랫브레드</option>
    
    </select>
    <h4>소스</h4>
    <input type="radio" name = "sauce" id = "sauce" value = "렌지">렌지
    <input type="radio" name = "sauce" id = "sauce" value = "마요네즈">마요네즈
    <input type="radio" name = "sauce" id = "sauce" value = "스위트어니언"> 스위트어니언
    <input type="radio" name = "sauce" id = "sauce" value = "스위트칠리"> 스위트칠리
    <input type="radio" name = "sauce" id = "sauce" value = "핫 칠리"> 핫 칠리
    <input type="radio" name = "sauce" id = "sauce" value = "올리브오일"> 올리브오일
    

    <h4>야채</h4>
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "양상추">양상추
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "토마토">토마토
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "오이">오이
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "피망">피망
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "양파">양파
    <input type="checkbox" name = "vegetable" id = "vegetable" value = "피클">피클

    <h4>음료</h4>
    <input type="radio" name = "drink"  id = "drink" value = "콜라">콜라
    <input type="radio" name = "drink"  id = "drink" value = "스프라이트">스프라이트
    <input type="radio" name = "drink"  id = "drink" value = "환타">환타
    <input type="radio" name = "drink"  id = "drink" value = "쿨피스">쿨피스
    <input type="radio" name = "drink"  id = "drink" value = "오렌지쥬스">오렌지쥬스
    <br>
    <hr>
    <input type= 'submit'>
</form>
{% endblock %}