Python/Framword(Django)/django_movie/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('movie/' , include('movie.urls')),
    path('admin/', admin.site.urls),
]

Python/Framword(Django)/django_movie/movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'
urlpatterns=[
    path('' , views.index , name = 'index'),
    path('movies/' ,views.movies, name = 'movies'),
    path('movies/<int:m_id>' , views.mtitle, name = 'moviesdetail'),
    path('new/' , views.new , name = 'new'),
    path('edit/<int:m_id>/' , views.edit, name = "edit" ),
    path('delete/<int:m_id>' , views.delete , name ="delete"),
    

]

Python/Framword(Django)/django_movie/movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    title_en = models.CharField(max_length=50)
    audience = models.IntegerField()
    open_date = models.DateTimeField()
    genre = models.CharField(max_length=30)
    watch_grade = models.CharField(max_length=20)
    score = models.FloatField()
    poster_url  = models.TextField()
    description = models.TextField()

Python/Framword(Django)/django_movie/movie/views.py
from django.shortcuts import render , redirect
from .models import Movie

# Create your views here.
def index(request):
    return render(request , 'movie/index.html'),
    
def movies(request):
    movie = Movie.objects.all()
    context = {
        'movie' : movie
    }
    return render(request , 'movie/movies.html' , context)

def mtitle(request , m_id):
    movie = Movie.objects.get(id=m_id)
    context = {
        'movie' : movie
    }
    return render(request , 'movie/mtitle.html' ,context)

def new(request):
    if request.method == "POST":
        title = request.POST.get("title")
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        movie = Movie()
        movie.title=title
        movie.title_en = title_en
        movie.audience = audience
        movie.open_date = open_date
        movie.genre = genre
        movie.watch_grade = watch_grade
        movie.score = score
        movie.poster_url = poster_url
        movie.description = description
        movie.save()

        return redirect('movie:movies')
    else:
        return render(request , 'movie/new.html')

def edit(request,m_id):
    movie = Movie.objects.get(id=m_id)
    if request.method=="POST":
        title = request.POST.get("title")
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        mm = Movie()
        mm.title=title
        mm.title_en = title_en
        mm.audience = audience
        mm.open_date = open_date
        mm.genre = genre
        mm.watch_grade = watch_grade
        mm.score = score
        mm.poster_url = poster_url
        mm.description = description
        mm.save()
        
    
        return redirect('movie:moviesdetail' , m_id)
    else:
        context = {
            'movie' : movie
        }
        return render(request , "movie/edit.html" , context)
def delete(request,m_id):
    movie = Movie.objects.get(id=m_id)
    movie.delete()

    return redirect("movie:movies")

Python/Framword(Django)/django_movie/movie/templates/movie/edit.html
{% extends 'base.html' %}
{% block body %}
    
<form action='{% url "movie:edit" movie.id %}' method = 'POST'>
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">title</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter title" name = 'title' value = "{{movie.title}}">
          
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">title_en</label>
          <input type="text" class="form-control" id="exampleInputPassword1" placeholder="title_en" name = "title_en" value = "{{movie.title_en}}">
        </div>

        <div class="form-group">
                <label for="exampleInputPassword1">audience</label>
                <input type="number" class="form-control" id="exampleInputPassword1" placeholder="audience" name = "audience" step  = "1000" value="{{movie.audience}}">
              </div>

        <div class="form-group">
            <label for="exampleInputPassword1">open_date</label>
            <input type="date" class="form-control" id="exampleInputPassword1" placeholder="open_date" name = "open_date" value= "{{movie.open_date}}">
            </div>
        
        <div class="form-group">
                <label for="exampleInputPassword1">genre</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="genre" name = "genre" value = "{{movie.genre}}">
                </div>

        <div class="form-group">
                <label for="exampleInputPassword1">watch_grade</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="wathc_grade" name = "watch_grade" value = "{{movie.watch_grade}}">
                </div> 

        <div class="form-group">
                <label for="exampleInputPassword1">scroe</label>
                <input type="number" class="form-control" id="exampleInputPassword1" placeholder="score" name = "score" max="100" value ="{{movie.score}}">
                </div>
        <div class="form-group">
                <label for="exampleInputPassword1">poster_url</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="poster_url" name = "poster_url" value = "{{movie.poster_url}}">
                </div>

        <div class="form-group">
                <label for="exampleInputPassword1">description</label>
                <input type="textarea" class="form-control" id="exampleInputPassword1" placeholder="description" name = "description" value="{{movie.description}}">
                </div>
        <button type="submit" class="btn btn-primary">영화 수정</button>
</form>
{% endblock %}

Python/Framword(Django)/django_movie/movie/templates/movie/index.html
{% extends 'base.html' %}
{% block body %}
<h1>index</h1>
{% endblock %}

Python/Framword(Django)/django_movie/movie/templates/movie/movies.html
{% extends 'base.html' %}
{% block body %}

<table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">movie</th>
            <th scope="col">title</th>
            <th scope="col">score</th>
            
          </tr>
        </thead>
        <tbody>
            {% for mo in movie%}
          <tr>
            
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'movie:moviesdetail' mo.id %}">{{ mo.title }}</a></td>
            <td>{{ mo.score}}</td>
            
          </tr>
            {% endfor %}   
        </tbody>
      </table>
      <a href="{% url 'movie:new' %}"  class="btn btn-primary">새 영화 등록 클릭</a>
{% endblock %}

Python/Framword(Django)/django_movie/movie/templates/movie/mtitle.html
{% extends 'base.html' %}
{% block body %}
<table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">1</th>
            <th scope="col">2</th>
            
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>제목</td>
            <td>{{movie.title}}</td>
            
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>영어제목</td>
            <td>{{movie.title_en}}</td>
           
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>관객수</td>
            <td>{{movie.audience}}</td>
            
          </tr>
          <tr>
                <th scope="row">4</th>
                <td>개봉일</td>
                <td>{{movie.open_date}}</td>
                
              </tr>
        <tr>
            <th scope="row">5</th>
            <td>장르</td>
            <td>genre</td>
            
         </tr>   
        <tr>
                <th scope="row">6</th>
                <td>연령</td>
                <td>{{movie.watch_grade}}</td>      
        </tr>   
        <tr>
                <th scope="row">7</th>
                <td>점수</td>
                <td>{{movie.score}}</td>      
        </tr>   

        <tr>
                <th scope="row">8</th>
                <td>포스터 url</td>
                <td>{{movie.poster_url}}</td>      
        </tr>   
        <tr>
                <th scope="row">9</th>
                <td>설명</td>
                <td>{{movie.description}}</td>      
        </tr>   
        </tbody>
       </table>
       <a href="{% url 'movie:movies' %}" class="btn btn-primary">영화목록</a>
       
       <a href="{% url 'movie:edit' movie.id %}" class="btn btn-primary">영화 수정</a>
       <a href="{% url 'movie:delete' movie.id %}" class="btn btn-primary">영화 삭제</a>
{% endblock %}

Python/Framword(Django)/django_movie/movie/templates/movie/new.html
{% extends 'base.html' %}
{% block body %}
    
<form action='{% url "movie:new" %}' method = 'POST'>
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">title</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter title" name = 'title'>
          
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">title_en</label>
          <input type="text" class="form-control" id="exampleInputPassword1" placeholder="title_en" name = "title_en">
        </div>

        <div class="form-group">
                <label for="exampleInputPassword1">audience</label>
                <input type="number" class="form-control" id="exampleInputPassword1" placeholder="audience" name = "audience" step  = "1000">
              </div>

        <div class="form-group">
            <label for="exampleInputPassword1">open_date</label>
            <input type="date" class="form-control" id="exampleInputPassword1" placeholder="open_date" name = "open_date">
            </div>
        
        <div class="form-group">
                <label for="exampleInputPassword1">genre</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="genre" name = "genre">
                </div>

        <div class="form-group">
                <label for="exampleInputPassword1">watch_grade</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="wathc_grade" name = "watch_grade">
                </div> 

        <div class="form-group">
                <label for="exampleInputPassword1">scroe</label>
                <input type="number" class="form-control" id="exampleInputPassword1" placeholder="score" name = "score" max="100">
                </div>
        <div class="form-group">
                <label for="exampleInputPassword1">poster_url</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="poster_url" name = "poster_url">
                </div>

        <div class="form-group">
                <label for="exampleInputPassword1">description</label>
                <input type="textarea" class="form-control" id="exampleInputPassword1" placeholder="description" name = "description">
                </div>
        <button type="submit" class="btn btn-primary">영화 등록</button>
</form>
{% endblock %}