Python/Framword(Django)/django_subway/config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
   
    path('btest/' ,include('btest.urls')),
    path('crud/' , include('crud.urls')),
    path('subway/' , include('subway.urls')),
    path('admin/', admin.site.urls),

]

Python/Framword(Django)/django_subway/crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'
urlpatterns = [
    path('' , views.index , name= 'index'), #crud/
    path('new/' , views.new , name = 'new'), #crud/new
    # path('create/' , views.create , name='create'), #crud/create
    path('<int:art_pk>/', views.detail , name= 'detail'), #crud/detail하게 내용 보는 페이지
    path("<int:art_pk>/update/", views.update ,  name = 'update'), # crud/update/ 수정하는 페이지
    # path("<int:pk>/revise/" , views.revise , name = 'revise'),
    path("<int:art_pk>/delete/" , views.delete , name = 'delete'),
    path("<int:art_id>/comment" , views.comment , name='comment'),
    #부모의 아이디는 art_id로 바꿔주겠다. 
    path('<int:art_id>/comment/<int:com_id>/edit/' , views.comedit, name = 'comedit'),
    path('<int:art_id>/comment/<int:com_id>/del/' , views.comdel, name = 'comdel'),

]

Python/Framword(Django)/django_subway/crud/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) #추가될때 마다 현재시간으로 저장
    updated_at = models.DateTimeField(auto_now=True) #editable옵션이 False로 자동 저장된다.

    def __str__(self):
        return f'{self.id} {self.title}'
  

class Comment(models.Model):
    comment = models.CharField(max_length=200)
    #ForeignKey(어떤 테이블 참조할지 , 그 테이블이 삭제될때 어떻게 할지!)
    #models.CASCADE : 부모테이블이 삭제시 같이 삭제하는 옵션
    #models.PROTECT : 부모테이블이 삭제될 때 오류를 발생(삭제가 되면 안되기 때문에!)
    #models.SET_NULL : 부모테이블이 삭제될때 null값을 채운다.(but not null 옵션일때는 불가능하다.)
    #models.SET() : 특정 함수를 호출.
    #models.DO_NOTHING : 암것도 안함.
    article = models.ForeignKey(Article , on_delete=models.CASCADE) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Python/Framword(Django)/django_subway/crud/views.py
from django.shortcuts import render , redirect
from .models import Article , Comment

# Create your views here.
def index(requests):
    # articles = Article.objects.all()
    #쿼리셋 형태로 전체 목록이 날아온다.

    #리스트 내용을 역순으로 하는 방법 1번째 파이썬에서 정렬 하는 방법
    # articles = Article.objects.all()[::-1]

    #리스트 내용을 역순으로 하는 방법 2번째 , 불러올때 정렬시키는 법
    articles = Article.objects.order_by('-id') 
    # 쿼리셋으로 리턴될때만 사용가능 , 값이 한 행만 날아오는 경우 제대로 작동하지않는다. 
    # 그래서 get의 경우 오류가 나지만 filter의 경우 오류가 안난다.

    context = {
        "articles" : articles,
    }
    return render (requests , "crud/index.html" , context)

def new(request):
    print(f'new : {request.method}')
    if request.method == 'POST':
        title = request.POST.get("title")
        content = request.POST.get("content")

        #DB에 저장시키자
        article = Article()
        
        article.title = title
        article.content = content
        article.save()
    

        return redirect('crud:index')
    else:
        return render(request , "crud/new.html")

#form 에서 데이터를 받아 DB에 저장하고 글작성 성공메세지 출력
    # def create(request):
    #     title = request.POST.get("title")
    #     content = request.POST.get("content")

    #     #DB에 저장시키자
    #     article = Article()
        
    #     article.title = title
    #     article.content = content
    #     article.save()
        

    #     return render(request, "crud/created.html")

def detail(request, art_pk):

    
    article = Article.objects.get(pk=art_pk) #앞은 table에 저장된 pk 뒤의 pk는 입력 받은 pk
    com = article.comment_set.all()
    comlen = len(com)

    #자동적으로 생기는 것은 id인데 왜 pk를 쓸수 있나?
    #id_exact = pk 로 등록이 되어있어 pk이용이 가능하다. 
    #만약 필터(filter)로 한다면 해당값은 쿼리셋으로 날아오기 떄문에 그 경우 for문을 사용해 주어야 한다.
    context = {
        "article" : article,
        "comments" : com,
        "comlen" : comlen,
    }
    return render(request, "crud/detail.html" , context)

def update(request, art_pk):
    
    if request.method == 'POST':
        article = Article.objects.get(pk=art_pk)

        title = request.POST.get("title")
        content = request.POST.get("content")

        #새로운 내용을 본 테이블의 해당 내역에 넣어준다.
        article.title = title
        article.content = content
        article.save()
        #save되면 바뀐 값이 최종으로 된다.

        return redirect('crud:detail',article.id) 
    else:
        print(f'update : {request.method}')
        article = Article.objects.get(pk=art_pk)
        context = {
            "article" : article,

        }
        return render(request , "crud/update.html" , context)

# def revise(request, pk): #pk받아오는 방법이 url에서 id 값 받아오는 것이다~
#     print(f'save : {request.method}')
#     article = Article.objects.get(pk=pk)

#     title = request.POST.get("title")
#     content = request.POST.get("content")

#     #새로운 내용을 본 테이블의 해당 내역에 넣어준다.
#     article.title = title
#     article.content = content
#     article.save()
#     #save되면 바뀐 값이 최종으로 된다.

#     return redirect('crud:detail',article.id) 

def delete(request, art_pk):
    article = Article.objects.get(pk=art_pk)
    
    if request.method == "POST":
        

        article.delete()

        return redirect('crud:index') #삭제해서 뭐 받아 올 필요도 없고 하니 바로 홈으로!
    else:
        return redirect('crud:detail' , article.id)


# 코멘트는 POST로 날아올 것이다. art_id/comment
def comment(request, art_id):
    article = Article.objects.get(id=art_id)

    if request.method == 'POST':
        comment = request.POST.get('comment')
        #comment에 해당 부분을 적용할 것이다.

        com = Comment()
        com.comment = comment
        com.article = article #부모 정보도 저장해준다.
        com.save()
    

        return redirect('crud:detail' , article.id) #art.id나 article.id나 상관없다!
        #return redirect('crud:detail',com.article_id) 이렇게 해도 된다! 
        #post일때만 저장이 될 것이다.
def comedit(request, art_id , com_id):
    com = Comment.objects.get(id=com_id) #커멘트의 id가 com_id랑 같은 것 만 가져온다.
    #간단하게 창을 만드는 것으로 해서

    if request.method =='POST':
        text =request.POST.get("comment")
        com.comment = text
        com.save()
        return redirect('crud:detail' , art_id)
    else:
        context = {
            'comment' : com

        }

        return render(request, 'crud/comedit.html' , context)
def comdel(request, art_id , com_id):
    com = Comment.objects.get(id = com_id)

    #POST형식으로 올때만 삭제를 해야하지 때문에
    if request.method == 'POST':
        com.delete()
        return redirect('crud:detail' , art_id)

Python/Framword(Django)/django_subway/crud/templates/crud/comedit.html
{% extends 'base.html' %}
{% block body %}
<form action='' method = 'POST'> <!--action이 빈값이면 현재 경로로 다시 -->
    {% csrf_token %}
    댓글 : <input type="text" name = "comment" value = "{{comment.comment}}">
    <input type= 'submit' value = "댓글수정">
</form>
{% endblock %}

Python/Framword(Django)/django_subway/crud/templates/crud/created.html
{% extends 'base.html' %}
{% block body %}
<h1>성공적인 입력!DB저장!</h1>
{% endblock %}

Python/Framword(Django)/django_subway/crud/templates/crud/detail.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ article.title}}</h1><br>
<hr>
{{ article.content }} <br>
<hr>
<!-- <a href="/crud/{{ article.pk }}/update/">수정하기</a> -->
<a href="{% url 'crud:update' article.id %}">수정하기</a>
<form action='{% url "crud:delete" article.id %}' method = 'POST'>
    {% csrf_token %}
    <input type= 'submit' value = "삭제하기" >
</form>
<!-- <a href="/crud/{{ article.pk }}/delete/">삭제하기</a> -->
<hr><br>

<form action='{% url "crud:comment" article.id %}'  method = 'POST'> 
    <!--어떤것이 부모테이블인지 넣어주어야 한다. 그렇기에 article의 값을 같이 넣어 줄 것이다.-->
    {% csrf_token %}
    댓글달기[{{ comlen }}]  : <input type="text" name = "comment" >
    <input type= 'submit'>
</form>

<hr><br>
<!-- 댓글이 많으면 오래걸리기 때문에 view에서 처리하자.-->
<!-- <ul>
    {% for com in article.comment_set.all %} 
        <li>{{com.comment}}</li>
    {% endfor %}
</ul>
<hr><br> -->
댓글 개수 : {{ comments|length }} / {{ article.comment_set.all|length}} / {{ comments.count}}
<ul>
    {% for com in comments %} <!-- 댓글이 많으면 오래걸리기 때문에 view에서 처리하자.-->
        <li>{{com.comment}}</li>
        <a href="{% url 'crud:comedit' article.id com.id %}">수정하기</a>
        <form action='{% url "crud:comdel" article.id com.id %}' method = 'POST'>
            {% csrf_token %}
            <input type= 'submit' value="삭제">
        </form>
        {% empty %}
            <h2>등록된 댓글이 없어요~</h2>
        {% endfor %}
</ul>
{% endblock %}

Python/Framword(Django)/django_subway/crud/templates/crud/index.html
{% extends 'base.html' %}

{% block body %}
<!-- <h1>Article List</h1>
<ul>
    {% for art in articles %}
    <li><a href="/crud/{{ art.pk }}/article">{{ art.id }}번글 {{ art.title }}</li></a> 해당 pk값이 들어갈 것 이다.-->
    <!-- {% endfor %}
</ul> --> 



<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col"> 번호</th>
        <th scope="col"> 제목</th>
        
      </tr>
    </thead>
    <tbody>
    {% for art in articles %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'crud:detail' art.pk %}">{{art.id}} 번글</a></td>
        <td><a href="{% url 'crud:detail' art.pk %}">{{art.title}}</a></td>
        
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endblock %}

Python/Framword(Django)/django_subway/crud/templates/crud/new.html
{% extends 'base.html' %}
{% block body %}
<form action='{% url "crud:new" %}' method = 'POST'>
    {% csrf_token %}
    <!-- <label for="title">기사제목</label> label은 id값과 매칭이 된다. -->
    <!-- <input type="text" name="title" id="title"><br> -->
    <!-- <textarea name="content" cols="30" rows="5"></textarea>30글자의 10줄 -->
    
    <div class="input-group input-group-lg">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroup-sizing-lg" >기사제목</span>
        </div>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name = "title">
      </div><br>
      <div class="input-group input-group-lg">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroup-sizing-lg" >기사내용</span>
        </div>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name= "content">
      </div>
    <input type="submit">
</form>
{% endblock %} 

Python/Framword(Django)/django_subway/crud/templates/crud/update.html
{% extends 'base.html' %}
{% block body %}
    <form action='{% url "crud:update" article.id %}' method = 'POST'><!--기본값또한 불러와야하기 때문에 pk값을 보낼 것이다.-->
        {% csrf_token %}
        <input type="text" name="title" value="{{ article.title }}" ><br>
        <textarea name="content" cols="30" rows="5">{{ article.content }}</textarea>
        <input type= 'submit'>
    </form>
{% endblock %}